version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: student-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: studentdb
    ports:
      - "3308:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
